services:
  cashtrack:
    build: .
    container_name: cashtrack
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://cashtrack:cashtrack@cashtrack-db:5432/cashtrack?sslmode=disable
      - CASHTRACK_ENV=production
    depends_on:
      - cashtrack-db

  cashtrack-db:
    image: postgres:16-alpine
    container_name: cashtrack-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cashtrack
      POSTGRES_USER: cashtrack
      POSTGRES_PASSWORD: cashtrack
    volumes:
      - cashtrack-db-data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  cashtrack-db-data: