services:
  backend:
    build:
      context: ../
      dockerfile: docker/backend.Dockerfile
    expose:
      - "8080"
    environment:
      - DATABASE_URL=postgres://cashtrack:cashtrack@db:5432/cashtrack?sslmode=disable

    depends_on:
      - db
    volumes:
      - ../backend:/app/backend

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    volumes:
      - ../frontend/src:/frontend/src
      - ../frontend/static:/frontend/static

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: cashtrack
      POSTGRES_USER: cashtrack
      POSTGRES_PASSWORD: cashtrack
    ports:
      - "15432:5432"
    volumes:
      - cashtrack-db-data:/var/lib/postgresql/data

volumes:
  cashtrack-db-data: