services:
  api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server.dev
    expose:
      - "8080"
    environment:
      - DATABASE_URL=postgres://cashtrack:cashtrack@db:5432/cashtrack?sslmode=disable

    depends_on:
      - db
    volumes:
      - ../server:/app/server

  ui:
    build:
      context: ../
      dockerfile: docker/Dockerfile.ui.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:8080
    depends_on:
      - api
    volumes:
      - ../client/src:/ui/client/src
      - ../client/static:/ui/client/static

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: cashtrack
      POSTGRES_USER: cashtrack
      POSTGRES_PASSWORD: cashtrack
    ports:
      - "15432:5432"
    volumes:
      - cashtrack-db-data:/var/lib/postgresql/data

volumes:
  cashtrack-db-data: