services:
  cashtrack:
    image: pochemuto/cashtrack:latest
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING=postgres://cashtrack:cashtrack@cashtrack-db:5432/cashtrack?sslmode=disable
      - CASHTRACK_ENV=production
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: cashtrack
      POSTGRES_USER: cashtrack
      POSTGRES_PASSWORD: cashtrack
    volumes:
      - cashtrack-db-data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  cashtrack-db-data: